
project_id = "sqmuydwkslyfuucjwjry"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
external_providers = false
additional_redirect_urls = ["https://127.0.0.1:3000/**"]
jwt_expiry = 3600
enable_manual_linking = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.figma]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""
url = ""
redirect_uri = ""

[edge-runtime]
enabled = true
port = 54330
ip_version = "ipv4"
policy = "per_worker"

[functions.binance-proxy]
verify_jwt = false
