// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqmuydwkslyfuucjwjry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbXV5ZHdrc2x5ZnV1Y2p3anJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzU0OTMsImV4cCI6MjA2NTU1MTQ5M30.Od4IHI0O2YQgSbywILTUOuvagSPd4jVgmZX1gJQGwXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);